# NumPy Practice Set

Practice questions based on Day 3 NumPy lecture. Each section maps to a topic covered in class. Try every question on your own before checking the lecture notes. Use the blank code cell beneath each question to write your solution.

**Setup — run this first:**

In [ ]:
import numpy as np
print("NumPy version:", np.__version__)

---
## Section 1 — Creating Arrays

**Q1.** Create a 1-D NumPy array containing the integers `5, 10, 15, 20, 25` from a Python list.

In [1]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(arr)

[ 5 10 15 20 25]


**Q2.** Create a 2-D array (matrix) with 3 rows and 4 columns, all filled with zeros.

In [2]:
import numpy as np
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Q3.** Create a 4×4 array completely filled with the value `9`.

In [3]:
import numpy as np
arr = np.full((4, 4), 9)
print(arr)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


**Q4.** Use `np.arange` to create an array of even numbers from 0 up to (but not including) 20.

In [4]:
import numpy as np
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


**Q5.** Use `np.linspace` to create an array of 9 evenly spaced numbers between 0 and 2 (both inclusive).

In [5]:
import numpy as np
arr = np.linspace(0, 2, 9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


**Q6.** Create a 5×5 identity matrix.

In [6]:
import numpy as np
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Q7.** Using `np.random.default_rng` with seed `7`, generate a 3×4 array of random integers between 1 and 100 (inclusive of 1, exclusive of 100).

In [7]:
import numpy as np
rng = np.random.default_rng(7)
arr = rng.integers(1, 100, size=(3, 4))
print(arr)

[[94 62 68 89]
 [58 77 83 23]
 [ 6 30 29 87]]


---
## Section 2 — Array Attributes & dtypes

**Q8.** For the array `A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])`, print its `ndim`, `shape`, `size`, `dtype`, and `nbytes`.

In [8]:
import numpy as np
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)
print(A.nbytes)

2
(2, 4)
8
int64
64


**Q9.** Create an array `[1.5, 2.7, 3.9, 4.2]` with dtype `float32`, then convert it to an integer array using `astype`. What values do you get, and why? (Add a short comment.)

In [9]:
import numpy as np
arr = np.array([1.5, 2.7, 3.9, 4.2], dtype=np.float32)
int_arr = arr.astype(int)
print(arr)
print(int_arr)

[1.5 2.7 3.9 4.2]
[1 2 3 4]


**Q10.** Create the array `[0, 1, 2, 0, 5]` and convert it to a boolean array. Predict the output before running.

In [10]:
import numpy as np
arr = np.array([0, 1, 2, 0, 5])
bool_arr = arr.astype(bool)
print(bool_arr)

[False  True  True False  True]


---
## Section 3 — Indexing & Slicing

**Q11.** Create `x = np.arange(100, 110)`. Extract: (a) the first element, (b) the last element, (c) elements from index 3 to 7, (d) every 3rd element, (e) the array reversed.

In [11]:
import numpy as np

x = np.arange(100, 110)
print(x[0])
print(x[-1])
print(x[3:8])
print(x[::3])
print(x[::-1])

100
109
[103 104 105 106 107]
[100 103 106 109]
[109 108 107 106 105 104 103 102 101 100]


**Q12.** Create `M = np.arange(1, 21).reshape(4, 5)`. Print the matrix, then extract:
- (a) the element at row 2, column 3
- (b) the entire second row
- (c) the entire third column
- (d) the sub-matrix consisting of the first 2 rows and last 3 columns
- (e) the last row

In [12]:
import numpy as np

M = np.arange(1, 21).reshape(4, 5)
print(M)
print(M[1, 2])
print(M[1])
print(M[:, 2])
print(M[:2, 2:])
print(M[-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
8
[ 6  7  8  9 10]
[ 3  8 13 18]
[[ 3  4  5]
 [ 8  9 10]]
[16 17 18 19 20]


**Q13.** From `M` above, extract every alternate row (rows 0, 2).

In [13]:
print(M[::2])

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


---
## Section 4 — Vectorized Operations (ufuncs)

**Q14.** Given `a = np.array([2, 4, 6, 8])` and `b = np.array([1, 3, 5, 7])`, compute element-wise: `a + b`, `a - b`, `a * b`, `a / b`, and `a ** 2`.

In [14]:
import numpy as np

a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[ 3  7 11 15]
[1 1 1 1]
[ 2 12 30 56]
[2.         1.33333333 1.2        1.14285714]
[ 4 16 36 64]


**Q15.** Compute the square root and natural logarithm of the array `[1, 4, 9, 16, 25]` using NumPy ufuncs.

In [15]:
import numpy as np

arr = np.array([1, 4, 9, 16, 25])
print(np.sqrt(arr))
print(np.log(arr))

[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]


**Q16.** Compute the dot product of `a = [1, 2, 3]` and `b = [4, 5, 6]` using the `@` operator.

In [16]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a @ b)

32


**Q17.** Speed test: use `%timeit` to compare cubing 500,000 numbers using a Python list comprehension vs a NumPy array.

In [17]:
import numpy as np

nums_list = list(range(500000))
nums_array = np.arange(500000)

%timeit [x**3 for x in nums_list]
%timeit nums_array**3

47.9 ms ± 1.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.37 ms ± 83.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


---
## Section 5 — Broadcasting

**Q18.** Add the scalar `100` to the array `[1, 2, 3, 4, 5]`.

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 100)

[101 102 103 104 105]


**Q19.** Add the 1-D array `[1, 2, 3]` to every row of the 2-D array `[[10, 20, 30], [40, 50, 60], [70, 80, 90]]`.

In [19]:
import numpy as np

a = np.array([1, 2, 3])
M = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(M + a)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


**Q20.** Create a column vector `[[1], [2], [3], [4]]` (shape `(4,1)`) and add it to the row vector `[10, 20, 30]` (shape `(3,)`). What is the resulting shape? Why?

In [20]:
import numpy as np

col = np.array([[1], [2], [3], [4]])
row = np.array([10, 20, 30])
result = col + row
print(result)
print(result.shape)

[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]
(4, 3)


**Q21.** Try adding a `(2, 3)` array and a `(4,)` array. Catch the `ValueError` with try/except and print the error message. Explain in a comment why broadcasting fails here.

In [21]:
import numpy as np

A = np.zeros((2, 3))
B = np.array([1, 2, 3, 4])

try:
    print(A + B)
except ValueError as e:
    print(e)
# Broadcasting fails because the shapes (2, 3) and (4,) are not compatible.

operands could not be broadcast together with shapes (2,3) (4,) 


---
## Section 6 — Aggregations & the `axis` Argument

**Q22.** Given
```python
M = np.array([[3, 7, 2, 8],
              [5, 1, 9, 4],
              [6, 0, 3, 2]])
```
Compute:
- (a) total sum of all elements
- (b) sum of each column
- (c) sum of each row
- (d) maximum of each row
- (e) minimum of each column

In [22]:
import numpy as np

M = np.array([[3, 7, 2, 8],
              [5, 1, 9, 4],
              [6, 0, 3, 2]])

print(np.sum(M))
print(np.sum(M, axis=0))
print(np.sum(M, axis=1))
print(np.max(M, axis=1))
print(np.min(M, axis=0))

50
[14  8 14 14]
[20 19 11]
[8 9 6]
[3 0 2 2]


**Q23.** For the same matrix `M`, find the index of the maximum element in each column using `argmax`.

In [23]:
print(np.argmax(M, axis=0))

[2 0 1 0]


**Q24.** Compute the overall mean and standard deviation of `M`, rounded to 2 decimal places.

In [24]:
print(round(np.mean(M), 2))
print(round(np.std(M), 2))

4.17
2.73


**Q25.** Compute the cumulative sum (`cumsum`) of `np.arange(1, 11)`.

In [25]:
print(np.arange(1, 11).cumsum())

[ 1  3  6 10 15 21 28 36 45 55]


---
## Section 7 — Mini Challenges 🚀

**Q26.** Create a 5×5 matrix where each element `M[i, j] = i + j` — without using a Python `for` loop. (Hint: broadcasting a column vector with a row vector.)

In [26]:
import numpy as np

i = np.arange(5).reshape(5, 1)
j = np.arange(5)
M = i + j
print(M)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


**Q27.** Generate a 1-D array of 20 random numbers drawn from a standard normal distribution (seed = 0). Then compute its mean, std, min, and max.

In [27]:
import numpy as np

rng = np.random.default_rng(0)
arr = rng.standard_normal(20)
print(arr)
print(arr.mean())
print(arr.std())
print(arr.min())
print(arr.max())

[ 0.12573022 -0.13210486  0.64042265  0.10490012 -0.53566937  0.36159505
  1.30400005  0.94708096 -0.70373524 -1.26542147 -0.62327446  0.04132598
 -2.32503077 -0.21879166 -1.24591095 -0.73226735 -0.54425898 -0.31630016
  0.41163054  1.04251337]
-0.18317831742872684
0.8508756897642668
-2.3250307746388343
1.3040000451301372


**Q28.** Normalize the columns of a 4×3 random matrix so that each column has mean 0 and standard deviation 1. (Use broadcasting — no loops.)

In [28]:
import numpy as np

rng = np.random.default_rng(0)
M = rng.random((4, 3))
normalized = (M - M.mean(axis=0)) / M.std(axis=0)
print(normalized)
print(normalized.mean(axis=0))
print(normalized.std(axis=0))

[[ 0.26472729 -1.7115202  -0.88665695]
 [-1.59826643  0.69009839  1.42728552]
 [ 0.17366687  0.31990792  0.44751433]
 [ 1.15987227  0.70151389 -0.98814291]]
[-1.11022302e-16 -3.33066907e-16 -1.38777878e-16]
[1. 1. 1.]


**Q29.** Given marks of 5 students in 3 subjects:
```python
marks = np.array([[78, 82, 90],
                  [65, 70, 72],
                  [88, 95, 92],
                  [54, 60, 58],
                  [80, 85, 87]])
```
Find: (a) each student's average, (b) each subject's average, (c) the index of the top-scoring student overall (highest total), (d) the subject in which the class performed best on average.

In [29]:
import numpy as np

marks = np.array([[78, 82, 90],
                  [65, 70, 72],
                  [88, 95, 92],
                  [54, 60, 58],
                  [80, 85, 87]])

student_avg = marks.mean(axis=1)
subject_avg = marks.mean(axis=0)
top_student = np.argmax(marks.sum(axis=1))
best_subject = np.argmax(subject_avg)

print(student_avg)
print(subject_avg)
print(top_student)
print(best_subject)

[83.33333333 69.         91.66666667 57.33333333 84.        ]
[73.  78.4 79.8]
2
2


**Q30.** Create a 10×10 multiplication table (where `M[i, j] = (i+1) * (j+1)`) using broadcasting only.

In [30]:
import numpy as np

i = np.arange(1, 11).reshape(10, 1)
j = np.arange(1, 11)
table = i * j
print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
